% prepare figure to be in the top left corner of the screen
% w/ a padding of 50px left and top
screenSize = get(0,'ScreenSize');
% sh = screenSize(4); % screen height
% sw = screenSize(3) % screen width
% fh = screenSize(4) *.8 % figure height
% fw = screenSize(3) *.75 % figure width 
ho = screenSize(4) - screenSize(4)*.8 - 50 ;% y-offset (height)
hFig = figure(	'Position',[ 50 ho screenSize(3) *.75,screenSize(4) *.8],...
	'Name','CERTool - auplot',...
	'NumberTitle','off',...
	'Tag','mainFigure',...
	'Menubar','none');% choose 'Menubar','figure' to run into trouble


hAxes = axes('Parent',hFig,...
	'Position',[0.05 0.05 0.9 0.9]);
		
set(hFig,'visible','off');
hold(hAxes,'on')

textSelectEmotion =	uicontrol('Style', 'text',...
	'String', 'Highlight AUs for emotions :',...
	'Units', 'normalized', ...
	'Position', [.05 .95 .15 .03],...
	'Visible','on',...
	'BackgroundColor',[.8 .8 .8], ...	
	'Tag','textSelectEmotion');   

selectEmotion =	uicontrol('Style', 'popup',...
	'String', 'None|Anger|Disgust|Fear|Happiness|Sadness|Surprise',...
	'Units', 'normalized', ...
	'Position', [.205 .955 .075 .03],...
	'Tag','selectEmo',...  
	'Tooltip','Use list to hightlight AUs relevant for basic emotions',...
	'Callback',@selectEmo);

buttonPrevious = uicontrol('Parent',hFig, ...
	'Units', 'normalized', ...
	'Position', [.425 .96 .05 .03],...
	'Style','pushbutton',... 
	'String','PREV.',...
	'HorizontalAlignment','center',...
	'Visible','on',...
	'Tooltip','Show previous epoch',...
	'Enable','on',...
	'Tag','prevButton');

textCurrent = uicontrol('Parent',hFig, ...
	'Units', 'normalized', ...
	'Position', [.475 .95 .075 .03],...
	'Style','Text',... 
	'String', sprintf('Trial %d',1),...
	'HorizontalAlignment','center',...
	'Visible','on',...
	'BackgroundColor',[.8 .8 .8], ...
	'Tag','textCurrent');

buttonNext = uicontrol('Parent',hFig, ...
	'Units', 'normalized', ...
	'Position', [.55 .96 .05 .03],...
	'Style','pushbutton',... 
	'String','NEXT',...
	'HorizontalAlignment','center',...
	'Visible','on',...
	'Tooltip','Show next epoch',...
	'Tag','nextButton');
	

buttonShowNW = uicontrol('Parent',hFig, ...
	'Units', 'normalized', ...
	'Position', [.65 .96 .1 .03],...
	'Style','pushbutton',... 
	'String','Network GUI',...
	'HorizontalAlignment','center',...
	'Visible','on',...
	'Tooltip','Open the current trial in NW GUI',...
	'Tag','buttonShowNW');

textCopy= uicontrol('Parent',hFig,...
	'Units', 'normalized', ...
	'Position',[.9 .001 .1 .02],...
	'Style','text',... 
	'Tag', 'textCopy ',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'FontSize',9,...
	'String','CERTool (c) 2013',...
	'ToolTip','people.physik.hu-berlin.de/~schinkel');